@startuml

skinparam ranksep 50
skinparam linetype ortho

struct game_settings_t

enum host_menu_options_t {
+ HOST_MENU_PUBLIC
+ HOST_MENU_PRIVATE
}

class host_menu_t {
{static} + host_menu(options: host_menu_options_t): game_settings_t*
{static} + host_menu_free_result(result: game_settings_t*): void
{static} - host_menu_clamp_coordinate(min: coordinate_t, val: coordinate_t, max: coordinate_t): coordinate_t
}
host_menu_t ..> game_settings_t : <<uses>>

enum main_menu_result_t {
+ MAIN_MENU_EXIT
+ MAIN_MENU_PRIVATE
+ MAIN_MENU_HOST
+ MAIN_MENU_JOIN_LOCAL
+ MAIN_MENU_JOIN_REMOTE
}

class main_menu {
{static} + main_menu(): main_menu_result_t
}

class connect_menu {
{static} + connect_menu_local(out_room_name: char*): bool
{static} + connect_menu_remote(out_hostname: char*, out_port: unsigned short*): bool
}

@enduml
