#ifndef INCLUDE_LIBSNAKE_CONSTANTS_H
#define INCLUDE_LIBSNAKE_CONSTANTS_H

#define MAX_PLAYERS 64

#define MAX_MAP_WIDTH 100
#define MAX_MAP_HEIGHT 80

#define MAX_CHANGELOG_SIZE (MAX_MAP_WIDTH * MAX_MAP_HEIGHT + MAX_PLAYERS)

#define SHM_NAME_BUFFER_SIZE 256
const char* SHM_NAME_FORMAT = "/shm-zemcik-snake-%s";

#endif
